/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ComponentDataResolver, ComponentHandle, EventFlowHistory, FormChangeDetail, FormField, FormSchema, LabelPosition } from "./types";
import { BasicFieldRenderer } from "./renderers/basic-field-renderer";
import { EventCenter } from "./managers/event-center";
import { EndpointManager } from "./managers/endpoint-manager";
export { ComponentDataResolver, ComponentHandle, EventFlowHistory, FormChangeDetail, FormField, FormSchema, LabelPosition } from "./types";
export { BasicFieldRenderer } from "./renderers/basic-field-renderer";
export { EventCenter } from "./managers/event-center";
export { EndpointManager } from "./managers/endpoint-manager";
export namespace Components {
    /**
     * 根据 JSON schema 渲染完整动态表单。
     */
    interface FormEasy {
        /**
          * 当前表单的基础字段渲染器。 undefined 使用全局渲染器，null 强制使用默认 H5 渲染。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 当前表单使用的事件中心。 未传入时使用全局共享事件中心；传入后可与其他表单隔离。
         */
        "eventCenter"?: EventCenter;
        /**
          * 描述表单及其字段的 JSON schema。
         */
        "schema": FormSchema;
        /**
          * 初始化完成后加载的表单预设值。
         */
        "value"?: Record<string, unknown>;
    }
    /**
     * 为数组字段提供添加和删除编辑功能。
     */
    interface FormEasyArray {
        /**
          * 当前表单指定的基础字段渲染器。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 是否禁用数组修改。
          * @default false
         */
        "disabled": boolean;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 共享事件路由器。
          * @default globalEventCenter
         */
        "eventCenter": EventCenter;
        /**
          * 数组字段定义。
         */
        "field": FormField;
        /**
          * 数组字段的唯一标识。
         */
        "fieldId": string;
        /**
          * 所属表单的键。
         */
        "formKey": string;
        /**
          * 字段标签相对于编辑器的位置。
          * @default 'left'
         */
        "labelPosition": LabelPosition;
        /**
          * 当前数组值。
         */
        "value": unknown;
    }
    /**
     * 渲染单个字段，并提供通用的 form-easy 组件操作。
     */
    interface FormEasyField {
        /**
          * 供事件中心或外部代码执行标准操作命令。
         */
        "applyHandle": (handle: ComponentHandle, value?: unknown, history?: EventFlowHistory) => Promise<void>;
        /**
          * 当前字段所属表单指定的基础字段渲染器。 undefined 使用全局渲染器，null 强制使用默认 H5 渲染。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 表单内所有字段共用的事件路由器。
          * @default globalEventCenter
         */
        "eventCenter": EventCenter;
        /**
          * 待渲染的字段定义。
         */
        "field": FormField;
        /**
          * 分配给当前字段的完整唯一标识。
         */
        "fieldId": string;
        /**
          * 用于解析事件源标识的表单键。
         */
        "formKey": string;
        /**
          * 字段标签相对于编辑器的位置。
          * @default 'left'
         */
        "labelPosition": LabelPosition;
        /**
          * 当前字段值。
         */
        "value": unknown;
    }
    /**
     * 将对象字段渲染为不含独立表单键和名称的嵌套表单。
     */
    interface FormEasyObject {
        /**
          * 当前表单指定的基础字段渲染器。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 是否禁用嵌套字段编辑。
          * @default false
         */
        "disabled": boolean;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 共享事件路由器。
          * @default globalEventCenter
         */
        "eventCenter": EventCenter;
        /**
          * 当前对象字段的标识前缀。
         */
        "fieldId": string;
        /**
          * 子字段定义列表。
          * @default []
         */
        "fields": FormField[];
        /**
          * 所属表单的键。
         */
        "formKey": string;
        /**
          * 字段标签相对于编辑器的位置。
          * @default 'left'
         */
        "labelPosition": LabelPosition;
        /**
          * 当前对象值。
         */
        "value": unknown;
    }
    /**
     * 使用 componentData 作为选项来源的默认 H5 下拉字段组件。
     */
    interface FormEasySelect {
        /**
          * 由字段组件数据加载机制提供的下拉选项。
         */
        "componentData": unknown;
        /**
          * 是否禁用当前控件。
          * @default false
         */
        "disabled": boolean;
        /**
          * 未选择值时展示的占位选项文本。
          * @default '请选择'
         */
        "placeholder": string;
        /**
          * 当前字段值。
         */
        "value": unknown;
    }
    /**
     * 使用端点管理器上传文件的默认 H5 基础字段组件。
     */
    interface FormEasyUpload {
        /**
          * 原生文件选择框接受的 MIME 类型或扩展名。
         */
        "accept"?: string;
        /**
          * 是否禁用当前控件。
          * @default false
         */
        "disabled": boolean;
        /**
          * 当前字段可调用异步服务的端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 当前字段配置。
         */
        "field": FormField;
        /**
          * 当前字段完整唯一标识。
         */
        "fieldId": string;
        /**
          * 当前所属表单键。
         */
        "formKey": string;
        /**
          * 是否允许一次选择多个文件。
          * @default false
         */
        "multiple": boolean;
        /**
          * 当前字段值；单文件为 URL，多文件为 URL 数组的 JSON 字符串。
         */
        "value": unknown;
    }
}
export interface FormEasyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormEasyElement;
}
export interface FormEasyArrayCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormEasyArrayElement;
}
export interface FormEasyFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormEasyFieldElement;
}
export interface FormEasyObjectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormEasyObjectElement;
}
export interface FormEasySelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormEasySelectElement;
}
export interface FormEasyUploadCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormEasyUploadElement;
}
declare global {
    interface HTMLFormEasyElementEventMap {
        "formChange": FormChangeDetail;
    }
    /**
     * 根据 JSON schema 渲染完整动态表单。
     */
    interface HTMLFormEasyElement extends Components.FormEasy, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormEasyElementEventMap>(type: K, listener: (this: HTMLFormEasyElement, ev: FormEasyCustomEvent<HTMLFormEasyElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormEasyElementEventMap>(type: K, listener: (this: HTMLFormEasyElement, ev: FormEasyCustomEvent<HTMLFormEasyElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormEasyElement: {
        prototype: HTMLFormEasyElement;
        new (): HTMLFormEasyElement;
    };
    interface HTMLFormEasyArrayElementEventMap {
        "valueChange": unknown[];
    }
    /**
     * 为数组字段提供添加和删除编辑功能。
     */
    interface HTMLFormEasyArrayElement extends Components.FormEasyArray, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormEasyArrayElementEventMap>(type: K, listener: (this: HTMLFormEasyArrayElement, ev: FormEasyArrayCustomEvent<HTMLFormEasyArrayElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormEasyArrayElementEventMap>(type: K, listener: (this: HTMLFormEasyArrayElement, ev: FormEasyArrayCustomEvent<HTMLFormEasyArrayElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormEasyArrayElement: {
        prototype: HTMLFormEasyArrayElement;
        new (): HTMLFormEasyArrayElement;
    };
    interface HTMLFormEasyFieldElementEventMap {
        "valueChange": unknown;
    }
    /**
     * 渲染单个字段，并提供通用的 form-easy 组件操作。
     */
    interface HTMLFormEasyFieldElement extends Components.FormEasyField, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormEasyFieldElementEventMap>(type: K, listener: (this: HTMLFormEasyFieldElement, ev: FormEasyFieldCustomEvent<HTMLFormEasyFieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormEasyFieldElementEventMap>(type: K, listener: (this: HTMLFormEasyFieldElement, ev: FormEasyFieldCustomEvent<HTMLFormEasyFieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormEasyFieldElement: {
        prototype: HTMLFormEasyFieldElement;
        new (): HTMLFormEasyFieldElement;
    };
    interface HTMLFormEasyObjectElementEventMap {
        "valueChange": Record<string, unknown>;
    }
    /**
     * 将对象字段渲染为不含独立表单键和名称的嵌套表单。
     */
    interface HTMLFormEasyObjectElement extends Components.FormEasyObject, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormEasyObjectElementEventMap>(type: K, listener: (this: HTMLFormEasyObjectElement, ev: FormEasyObjectCustomEvent<HTMLFormEasyObjectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormEasyObjectElementEventMap>(type: K, listener: (this: HTMLFormEasyObjectElement, ev: FormEasyObjectCustomEvent<HTMLFormEasyObjectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormEasyObjectElement: {
        prototype: HTMLFormEasyObjectElement;
        new (): HTMLFormEasyObjectElement;
    };
    interface HTMLFormEasySelectElementEventMap {
        "valueChange": string | number;
    }
    /**
     * 使用 componentData 作为选项来源的默认 H5 下拉字段组件。
     */
    interface HTMLFormEasySelectElement extends Components.FormEasySelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormEasySelectElementEventMap>(type: K, listener: (this: HTMLFormEasySelectElement, ev: FormEasySelectCustomEvent<HTMLFormEasySelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormEasySelectElementEventMap>(type: K, listener: (this: HTMLFormEasySelectElement, ev: FormEasySelectCustomEvent<HTMLFormEasySelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormEasySelectElement: {
        prototype: HTMLFormEasySelectElement;
        new (): HTMLFormEasySelectElement;
    };
    interface HTMLFormEasyUploadElementEventMap {
        "valueChange": string;
    }
    /**
     * 使用端点管理器上传文件的默认 H5 基础字段组件。
     */
    interface HTMLFormEasyUploadElement extends Components.FormEasyUpload, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormEasyUploadElementEventMap>(type: K, listener: (this: HTMLFormEasyUploadElement, ev: FormEasyUploadCustomEvent<HTMLFormEasyUploadElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormEasyUploadElementEventMap>(type: K, listener: (this: HTMLFormEasyUploadElement, ev: FormEasyUploadCustomEvent<HTMLFormEasyUploadElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormEasyUploadElement: {
        prototype: HTMLFormEasyUploadElement;
        new (): HTMLFormEasyUploadElement;
    };
    interface HTMLElementTagNameMap {
        "form-easy": HTMLFormEasyElement;
        "form-easy-array": HTMLFormEasyArrayElement;
        "form-easy-field": HTMLFormEasyFieldElement;
        "form-easy-object": HTMLFormEasyObjectElement;
        "form-easy-select": HTMLFormEasySelectElement;
        "form-easy-upload": HTMLFormEasyUploadElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * 根据 JSON schema 渲染完整动态表单。
     */
    interface FormEasy {
        /**
          * 当前表单的基础字段渲染器。 undefined 使用全局渲染器，null 强制使用默认 H5 渲染。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 当前表单使用的事件中心。 未传入时使用全局共享事件中心；传入后可与其他表单隔离。
         */
        "eventCenter"?: EventCenter;
        /**
          * 每次值变更时触发字段和完整表单上下文。
         */
        "onFormChange"?: (event: FormEasyCustomEvent<FormChangeDetail>) => void;
        /**
          * 描述表单及其字段的 JSON schema。
         */
        "schema": FormSchema;
        /**
          * 初始化完成后加载的表单预设值。
         */
        "value"?: Record<string, unknown>;
    }
    /**
     * 为数组字段提供添加和删除编辑功能。
     */
    interface FormEasyArray {
        /**
          * 当前表单指定的基础字段渲染器。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 是否禁用数组修改。
          * @default false
         */
        "disabled"?: boolean;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 共享事件路由器。
          * @default globalEventCenter
         */
        "eventCenter"?: EventCenter;
        /**
          * 数组字段定义。
         */
        "field": FormField;
        /**
          * 数组字段的唯一标识。
         */
        "fieldId": string;
        /**
          * 所属表单的键。
         */
        "formKey": string;
        /**
          * 字段标签相对于编辑器的位置。
          * @default 'left'
         */
        "labelPosition"?: LabelPosition;
        /**
          * 数组变更后触发新的数组值。
         */
        "onValueChange"?: (event: FormEasyArrayCustomEvent<unknown[]>) => void;
        /**
          * 当前数组值。
         */
        "value"?: unknown;
    }
    /**
     * 渲染单个字段，并提供通用的 form-easy 组件操作。
     */
    interface FormEasyField {
        /**
          * 当前字段所属表单指定的基础字段渲染器。 undefined 使用全局渲染器，null 强制使用默认 H5 渲染。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 表单内所有字段共用的事件路由器。
          * @default globalEventCenter
         */
        "eventCenter"?: EventCenter;
        /**
          * 待渲染的字段定义。
         */
        "field": FormField;
        /**
          * 分配给当前字段的完整唯一标识。
         */
        "fieldId": string;
        /**
          * 用于解析事件源标识的表单键。
         */
        "formKey": string;
        /**
          * 字段标签相对于编辑器的位置。
          * @default 'left'
         */
        "labelPosition"?: LabelPosition;
        /**
          * 向父级渲染器通知字段值变更。
         */
        "onValueChange"?: (event: FormEasyFieldCustomEvent<unknown>) => void;
        /**
          * 当前字段值。
         */
        "value"?: unknown;
    }
    /**
     * 将对象字段渲染为不含独立表单键和名称的嵌套表单。
     */
    interface FormEasyObject {
        /**
          * 当前表单指定的基础字段渲染器。
         */
        "basicFieldRenderer"?: BasicFieldRenderer | null;
        /**
          * 当前表单覆盖全局配置的组件数据解析器。
         */
        "componentDataResolver"?: ComponentDataResolver;
        /**
          * 是否禁用嵌套字段编辑。
          * @default false
         */
        "disabled"?: boolean;
        /**
          * 当前表单覆盖全局配置的异步服务端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 共享事件路由器。
          * @default globalEventCenter
         */
        "eventCenter"?: EventCenter;
        /**
          * 当前对象字段的标识前缀。
         */
        "fieldId": string;
        /**
          * 子字段定义列表。
          * @default []
         */
        "fields"?: FormField[];
        /**
          * 所属表单的键。
         */
        "formKey": string;
        /**
          * 字段标签相对于编辑器的位置。
          * @default 'left'
         */
        "labelPosition"?: LabelPosition;
        /**
          * 子字段变更后触发完整的嵌套对象。
         */
        "onValueChange"?: (event: FormEasyObjectCustomEvent<Record<string, unknown>>) => void;
        /**
          * 当前对象值。
         */
        "value"?: unknown;
    }
    /**
     * 使用 componentData 作为选项来源的默认 H5 下拉字段组件。
     */
    interface FormEasySelect {
        /**
          * 由字段组件数据加载机制提供的下拉选项。
         */
        "componentData"?: unknown;
        /**
          * 是否禁用当前控件。
          * @default false
         */
        "disabled"?: boolean;
        /**
          * 值变更时通知 form-easy 字段。
         */
        "onValueChange"?: (event: FormEasySelectCustomEvent<string | number>) => void;
        /**
          * 未选择值时展示的占位选项文本。
          * @default '请选择'
         */
        "placeholder"?: string;
        /**
          * 当前字段值。
         */
        "value"?: unknown;
    }
    /**
     * 使用端点管理器上传文件的默认 H5 基础字段组件。
     */
    interface FormEasyUpload {
        /**
          * 原生文件选择框接受的 MIME 类型或扩展名。
         */
        "accept"?: string;
        /**
          * 是否禁用当前控件。
          * @default false
         */
        "disabled"?: boolean;
        /**
          * 当前字段可调用异步服务的端点管理器。
         */
        "endpointManager"?: EndpointManager;
        /**
          * 当前字段配置。
         */
        "field": FormField;
        /**
          * 当前字段完整唯一标识。
         */
        "fieldId": string;
        /**
          * 当前所属表单键。
         */
        "formKey": string;
        /**
          * 是否允许一次选择多个文件。
          * @default false
         */
        "multiple"?: boolean;
        /**
          * 上传完成后通知 form-easy 字段更新值。
         */
        "onValueChange"?: (event: FormEasyUploadCustomEvent<string>) => void;
        /**
          * 当前字段值；单文件为 URL，多文件为 URL 数组的 JSON 字符串。
         */
        "value"?: unknown;
    }

    interface FormEasyArrayAttributes {
        "fieldId": string;
        "formKey": string;
        "labelPosition": LabelPosition;
        "disabled": boolean;
    }
    interface FormEasyFieldAttributes {
        "fieldId": string;
        "formKey": string;
        "labelPosition": LabelPosition;
    }
    interface FormEasyObjectAttributes {
        "fieldId": string;
        "formKey": string;
        "labelPosition": LabelPosition;
        "disabled": boolean;
    }
    interface FormEasySelectAttributes {
        "disabled": boolean;
        "placeholder": string;
    }
    interface FormEasyUploadAttributes {
        "multiple": boolean;
        "accept": string;
        "disabled": boolean;
        "fieldId": string;
        "formKey": string;
    }

    interface IntrinsicElements {
        "form-easy": FormEasy;
        "form-easy-array": Omit<FormEasyArray, keyof FormEasyArrayAttributes> & { [K in keyof FormEasyArray & keyof FormEasyArrayAttributes]?: FormEasyArray[K] } & { [K in keyof FormEasyArray & keyof FormEasyArrayAttributes as `attr:${K}`]?: FormEasyArrayAttributes[K] } & { [K in keyof FormEasyArray & keyof FormEasyArrayAttributes as `prop:${K}`]?: FormEasyArray[K] } & OneOf<"fieldId", FormEasyArray["fieldId"], FormEasyArrayAttributes["fieldId"]> & OneOf<"formKey", FormEasyArray["formKey"], FormEasyArrayAttributes["formKey"]>;
        "form-easy-field": Omit<FormEasyField, keyof FormEasyFieldAttributes> & { [K in keyof FormEasyField & keyof FormEasyFieldAttributes]?: FormEasyField[K] } & { [K in keyof FormEasyField & keyof FormEasyFieldAttributes as `attr:${K}`]?: FormEasyFieldAttributes[K] } & { [K in keyof FormEasyField & keyof FormEasyFieldAttributes as `prop:${K}`]?: FormEasyField[K] } & OneOf<"fieldId", FormEasyField["fieldId"], FormEasyFieldAttributes["fieldId"]> & OneOf<"formKey", FormEasyField["formKey"], FormEasyFieldAttributes["formKey"]>;
        "form-easy-object": Omit<FormEasyObject, keyof FormEasyObjectAttributes> & { [K in keyof FormEasyObject & keyof FormEasyObjectAttributes]?: FormEasyObject[K] } & { [K in keyof FormEasyObject & keyof FormEasyObjectAttributes as `attr:${K}`]?: FormEasyObjectAttributes[K] } & { [K in keyof FormEasyObject & keyof FormEasyObjectAttributes as `prop:${K}`]?: FormEasyObject[K] } & OneOf<"fieldId", FormEasyObject["fieldId"], FormEasyObjectAttributes["fieldId"]> & OneOf<"formKey", FormEasyObject["formKey"], FormEasyObjectAttributes["formKey"]>;
        "form-easy-select": Omit<FormEasySelect, keyof FormEasySelectAttributes> & { [K in keyof FormEasySelect & keyof FormEasySelectAttributes]?: FormEasySelect[K] } & { [K in keyof FormEasySelect & keyof FormEasySelectAttributes as `attr:${K}`]?: FormEasySelectAttributes[K] } & { [K in keyof FormEasySelect & keyof FormEasySelectAttributes as `prop:${K}`]?: FormEasySelect[K] };
        "form-easy-upload": Omit<FormEasyUpload, keyof FormEasyUploadAttributes> & { [K in keyof FormEasyUpload & keyof FormEasyUploadAttributes]?: FormEasyUpload[K] } & { [K in keyof FormEasyUpload & keyof FormEasyUploadAttributes as `attr:${K}`]?: FormEasyUploadAttributes[K] } & { [K in keyof FormEasyUpload & keyof FormEasyUploadAttributes as `prop:${K}`]?: FormEasyUpload[K] } & OneOf<"fieldId", FormEasyUpload["fieldId"], FormEasyUploadAttributes["fieldId"]> & OneOf<"formKey", FormEasyUpload["formKey"], FormEasyUploadAttributes["formKey"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * 根据 JSON schema 渲染完整动态表单。
             */
            "form-easy": LocalJSX.IntrinsicElements["form-easy"] & JSXBase.HTMLAttributes<HTMLFormEasyElement>;
            /**
             * 为数组字段提供添加和删除编辑功能。
             */
            "form-easy-array": LocalJSX.IntrinsicElements["form-easy-array"] & JSXBase.HTMLAttributes<HTMLFormEasyArrayElement>;
            /**
             * 渲染单个字段，并提供通用的 form-easy 组件操作。
             */
            "form-easy-field": LocalJSX.IntrinsicElements["form-easy-field"] & JSXBase.HTMLAttributes<HTMLFormEasyFieldElement>;
            /**
             * 将对象字段渲染为不含独立表单键和名称的嵌套表单。
             */
            "form-easy-object": LocalJSX.IntrinsicElements["form-easy-object"] & JSXBase.HTMLAttributes<HTMLFormEasyObjectElement>;
            /**
             * 使用 componentData 作为选项来源的默认 H5 下拉字段组件。
             */
            "form-easy-select": LocalJSX.IntrinsicElements["form-easy-select"] & JSXBase.HTMLAttributes<HTMLFormEasySelectElement>;
            /**
             * 使用端点管理器上传文件的默认 H5 基础字段组件。
             */
            "form-easy-upload": LocalJSX.IntrinsicElements["form-easy-upload"] & JSXBase.HTMLAttributes<HTMLFormEasyUploadElement>;
        }
    }
}
